name: "Provision & Deploy"

on:
  push:
    branches: ["master"]

permissions:
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5

      - name: Setup SSH agent
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Generate Ansible inventory
        run: |
          IP=$(curl -s \
            -H "Authorization: Bearer ${{ secrets.TF_API_TOKEN }}" \
            "https://app.terraform.io/api/v2/workspaces/${{ vars.TF_WORKSPACE_ID }}/current-state-version-outputs" \
            | jq -r '.data[] | select(.attributes.name=="instance_ip") | .attributes.value')
          echo "::add-mask::$IP"
          echo "[linode]" > ansible/inventory.ini
          echo "stirling-pdf ansible_host=$IP ansible_user=marcus" >> ansible/inventory.ini

      - name: Install Ansible collections
        working-directory: ansible
        run: ansible-galaxy collection install -r requirements.yml

      - name: Ansible Provisioning
        working-directory: ansible
        run: ansible-playbook playbooks/site.yml
